<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise</title>
</head>
<body>
    <script>
    //     //関数
    //     function test1(){
    //         return '関数１';
    //     };
    //     console.log(test1());
        
    //     //定数などに入れる
    //     const test2 = () => {
    //         return '関数２';
    //     }
    //     console.log(test2());
        
    //     // Promise
    //     //1 状態（OK　or NG）
    //     //2 promiseチェーン
    //    function promiseTest1(){
    //        return new Promise((ok) => {
    //            //引数には状態（OK　OR　NG）
    //            ok('Promise1ですよ');
    //        });
    //    } 
    //    console.log(promiseTest1());

    //    const promiseTest2 = new Promise( ok=> {
    //        ok('Promise2ですよ');
    //    })
    //    console.log(promiseTest2);

    //    //inputあり
    //    function promiseTest3(input){
    //        return new Promise((resolve) =>{
    //            resolve(`プロミス${input}です`);
    //        })
    //    }
    //    console.log(promiseTest3('様のお通り'));
    

    //Promiseチェーン
    // Promise.then(ok_callback, ng_callback)
    // Promise.then((ok_value) => {}, (ng_reason) => {})
    // Promise.catch((ng_reason) => {})//NGはキャッチ
    //ngも追加
    // new Promise((ok,ng) => {})

    // function promiseTest4(pay){
    //     return new Promise( (resolve,reject) => {
    //         if (pay > 100){
    //             let change = pay - 100;
    //             resolve(change);
    //         }
    //         reject('お金が足りません');
    //     })
    // }
    // console.log(promiseTest4(100).catch((e) => {console.log(e)}));//error

    // promiseTest4(80).then( test4result =>{//400-100 === 300 .then(300 =>{})
    //     console.log(test4result);//promiseTest4の値＝＝input-100 から更に100引いた値 300 - 100 == 200
    //     return promiseTest4(test4result);//returnによってPromiseでラップされているので、さらにthenが使える状態でreturnする
    //     //test4result=== 200のまま
    // }).then( changeAgain=> { //changeAgain == promiseTest4(test4result)
    //     console.log(changeAgain);//resultOfResult === 200
    // }).catch((e)=> {console.log(e)});

    function promiseTest(pay,sec){
        return new Promise((resolve, reject) => {

                setTimeout(()=>{
                    if (pay > 100){
                        let change = pay - 100;
                        console.log(`${sec}秒、お釣りは${change}円です`);
                        resolve(change);
                    }else{
                        reject('お金が足りません');
                    }
                }, sec * 1000)
            }
        )
    }
    console.log(1);
    promiseTest(300,2)
    .then( (change1) =>promiseTest(change1,3))
    .then( (change2) =>promiseTest(change2,5))
    .catch(e => console.log(e));
    console.log(3);
    </script>
</body>
</html>